module.exports = {
  REGISTER_WITH_SERVER: 'REGISTER_WITH_SERVER',
  UPDATE_CONNECTED_PLAYERS: 'UPDATE_CONNECTED_PLAYERS', 
  
  // below are not in use yet
  OBTAIN_INVITE: 'OBTAIN_INVITE',
  SUBMIT_INVITE: 'SUBMIT_INVITE',
  LOGIN: 'LOGIN',
};