module.exports = {
  // System
  REGISTER_WITH_SERVER: 'REGISTER_WITH_SERVER',
  UPDATE_CONNECTED_PLAYERS: 'UPDATE_CONNECTED_PLAYERS',
  SET_INITIAL_DATA: 'SET_INITIAL_DATA',

  // Players
  SET_PLAYERS: 'SET_PLAYERS'
};